apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name:  ws-monitor
  namespace: default
  labels:
    app: ws-monitor
    release: prometheus-stack
spec:
  jobLabel: ws-metrics
  selector:
    matchLabels:
      app: wsk-svc
      release: prometheus-stack
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: metrics
    path: /metrics