apiVersion: v1
kind: Service
metadata:
  name: wsk-svc
spec:
  selector:
    app: wsk-base
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10
  ports:
    - name: default
      protocol: TCP
      port: 3000
      targetPort: 5000
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
  #     nodePort: 30000
  # type: NodePort
