apiVersion: apps/v1
kind: Deployment
metadata:
  name: wsk-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wsk-base
  template:
    metadata:
      labels:
        app: wsk-base
        track: stable
        version: 0.1.1
    spec:
      containers:
        - name: websocket-base
          image: "wsk-base"
          imagePullPolicy: Never
          env:
          - name: REDIS_HOST
            value: "redis-master.default.svc"
          ports:
          - name: websocket
            containerPort: 5000
