version: '3.2'
services:
  socket-server:
    # build: .
    image: sw360cab/wsk-base:0.1.1
    restart: always
    deploy:
      mode: replicated
      replicas: 2
    environment:
      - "REDIS_HOST=redis"
  
  # socket-server2:
  #   image: sw360cab/wsk-base:0.1.1
  #   container_name: socket-server2
  #   restart: always
  #   environment:
  #     - "REDIS_HOST=redis"

  proxy:
    image: haproxy:1
    container_name: proxy
    ports:
      - 80:80
    restart: always
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg  
    depends_on:
      - socket-server

  redis:
    image: redis:5.0